import type { Metadata } from "next";
import { Geist, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar"
import ToasterProvider from "./ToasterProvider"
import Footer from "./component/Footer"

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Library",
  description: "Generated by Vidhi",
  icons: {
    icon: "/title.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
            <div className="flex">
    
			{/* Left Sidebar */}
			{/* <Navbar /> */}

			{/* Main Content */}
			<main className="flex-1 ">
			  {children}
			  <ToasterProvider />
			</main>
			

		  </div>
      </body>
    </html>
  );
}
