import type { Metadata } from "next";
import { Geist, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar"
import ToasterProvider from "./ToasterProvider"

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Library",
  description: "Generated by Vidhi",
  icons: {
    icon: "/title.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
              <div className="fixed top-0 left-0 w-full z-50">
                  <Navbar />
              </div>

              {/* Push content below navbar */}
              <div className="pt-16">
                  {children}
                  <ToasterProvider/>
              </div>
      </body>
    </html>
  );
}
